### ISSUE TITLE
Inference command

### ISSUE THREAD

**Issue by crenaudineau1** [Kibeom-Hong/Domain-Aware-Style-Transfer#2]
Hello,

Your paper is amazing, nice works ! Could you  release on Readme the Test inference command ?

I read your main.py but I don't know how to make an artistic style transfer ? Could you provide a command example for a simple style transfert ?

Thanks a lot.

**Comment by crenaudineau1** [comment]
I found the scripts folder, but pretrained model are missing for a quick inference. Could you release theses ?

**Comment by Kibeom-Hong** [comment]
Thanks for your interesting!

We update the inference command and pre-trained weights right before!

It's my first time to upload the github. So If you have any problem during the inference step, please feel free to tell me :)

Thanks.
