### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 33KU** [Kibeom-Hong/Domain-Aware-Style-Transfer#6]
Hello, where can I get the dataset?

**Comment by Kibeom-Hong** [comment]
We used two dataets : WikiArt (for artistic) and MSCoCo (for photo-realistic)

Here are the links:
**WikiArt dataset**
https://github.com/cs-chan/ArtGAN/blob/master/WikiArt%20Dataset/README.md

**MSCoCo dataset**
https://cocodataset.org/#home

**Comment by 33KU** [comment]
> We used two dataets : WikiArt (for artistic) and MSCoCo (for photo-realistic)
> 
> Here are the links:
> **WikiArt dataset**
> https://github.com/cs-chan/ArtGAN/blob/master/WikiArt%20Dataset/README.md
> 
> **MSCoCo dataset**
> https://cocodataset.org/#home

Thanks for your reply.
