### ISSUE TITLE
Training process.

### ISSUE THREAD

**Issue by sunwoo76** [Kibeom-Hong/Domain-Aware-Style-Transfer#7]
Hi. 

I have a question.

Did you use the total loss or only reconstruction loss when you train your decoder for reconstruction?

Reconstruction and stylization are both trained?

thanks.

**Comment by Kibeom-Hong** [comment]
Thanks for interesting my research.

I used the total loss for only reconstruction tasks.

Since this work is for arbitrary style transfer, our networks is trained only for reconstruction. (not stylization)

The only stylization is conducted by the transformer.
